version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_mtg
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/MTG
      - RABBITMQ_URI=amqp://rabbitmq:5672
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6.0
    container_name: mongo_mtg
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_mtg
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
